version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rag_api
    ports:
      - "7000:7000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./server/src/config.yml:/app/src/config.yml:ro
      - ./server/src/prompts.yml:/app/src/prompts.yml:ro
      - ./server/src/scenarios:/app/src/scenarios:ro
      - ./data:/app/data:ro
    networks:
      - rag_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: rag_frontend
    ports:
      - "7001:7001"
    depends_on:
      - api
    networks:
      - rag_network
    restart: unless-stopped

networks:
  rag_network:
    driver: bridge
