llm:
  url: https://openrouter.ai/api/v1
  model: google/gemini-2.5-flash
  token:

qdrant:
  host: localhost
  port: 6333
  collection_name: documents
  model_name: all-MiniLM-L6-v2
  vector_size: 384
  top_samples: 10

logging:
    app_name: RAG-bot
    graylog:
      enabled: false
      udp: false
      host: 0.0.0.0
      port: 12201
    console:
      enabled: true
    root_level: INFO
    levels:
      httpx: WARN
      openai: WARN
      uvicorn.access: WARN