llm:
  url: https://openrouter.ai/api/v1
  model: qwen/qwen3-30b-a3b-instruct-2507
  token: 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

qdrant:
  host: localhost
  port: 6333
  collection_name: documents
  model_name: all-MiniLM-L6-v2
  vector_size: 384
  top_samples: 10

logging:
    app_name: RAG-bot
    graylog:
      enabled: false
      udp: false
      host: 0.0.0.0
      port: 12201
    console:
      enabled: true
    root_level: INFO
    levels:
      httpx: WARN
      openai: WARN
      uvicorn.access: WARN